"""plattform_modus_spalte

Revision ID: 3118d3d0c138
Revises: a1c01bf7c118
Create Date: 2026-05-15 21:06:34.994662

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '3118d3d0c138'
down_revision: str | None = 'a1c01bf7c118'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulationen', sa.Column('plattform_modus', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulationen', 'plattform_modus')
    # ### end Alembic commands ###
