"""nutzer_tabelle

Revision ID: 4d5672f1da9f
Revises: 4daa68489fdf
Create Date: 2026-05-15 22:05:00.698464

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4d5672f1da9f'
down_revision: str | None = '4daa68489fdf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutzer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('passwort_hash', sa.String(length=200), nullable=False),
    sa.Column('anzeige_name', sa.String(length=120), nullable=False),
    sa.Column('rolle', sa.String(length=20), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutzer_email'), 'nutzer', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutzer_email'), table_name='nutzer')
    op.drop_table('nutzer')
    # ### end Alembic commands ###
