"""audit_log

Revision ID: 4daa68489fdf
Revises: 3118d3d0c138
Create Date: 2026-05-15 21:52:18.747169

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4daa68489fdf'
down_revision: str | None = '3118d3d0c138'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zeitstempel', sa.DateTime(), nullable=False),
    sa.Column('aktion', sa.String(length=80), nullable=False),
    sa.Column('ressource', sa.String(length=80), nullable=False),
    sa.Column('ressource_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_aktion'), 'audit_log', ['aktion'], unique=False)
    op.create_index(op.f('ix_audit_log_ressource'), 'audit_log', ['ressource'], unique=False)
    op.create_index(op.f('ix_audit_log_ressource_id'), 'audit_log', ['ressource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_zeitstempel'), 'audit_log', ['zeitstempel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_zeitstempel'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_ressource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_ressource'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_aktion'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
