"""graphrag_tabellen

Revision ID: 8d15840e6016
Revises: 90850ef95722
Create Date: 2026-05-15 20:39:25.423265

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '8d15840e6016'
down_revision: str | None = '90850ef95722'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beziehungen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('von', sa.String(length=200), nullable=False),
    sa.Column('nach', sa.String(length=200), nullable=False),
    sa.Column('art', sa.String(length=80), nullable=False),
    sa.Column('gewicht', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beziehungen_nach'), 'beziehungen', ['nach'], unique=False)
    op.create_index(op.f('ix_beziehungen_von'), 'beziehungen', ['von'], unique=False)
    op.create_table('entitaeten',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('typ', sa.String(length=40), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitaeten_name'), 'entitaeten', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entitaeten_name'), table_name='entitaeten')
    op.drop_table('entitaeten')
    op.drop_index(op.f('ix_beziehungen_von'), table_name='beziehungen')
    op.drop_index(op.f('ix_beziehungen_nach'), table_name='beziehungen')
    op.drop_table('beziehungen')
    # ### end Alembic commands ###
