"""initiales_schema

Revision ID: 90850ef95722
Revises: 
Create Date: 2026-05-15 20:29:15.629303

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '90850ef95722'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenten',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('persona_json', sa.Text(), nullable=False),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulationen',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('agent_ids_json', sa.Text(), nullable=False),
    sa.Column('schritte', sa.Integer(), nullable=False),
    sa.Column('variable_json', sa.JSON(), nullable=False),
    sa.Column('dual_modus', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gedaechtnis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agenten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations_schritte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('nummer', sa.Integer(), nullable=False),
    sa.Column('welt', sa.String(length=20), nullable=False),
    sa.Column('ereignisse_json', sa.Text(), nullable=False),
    sa.Column('agent_zustaende_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulationen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulations_schritte')
    op.drop_table('gedaechtnis')
    op.drop_table('simulationen')
    op.drop_table('agenten')
    # ### end Alembic commands ###
