"""plattform_simulation

Revision ID: a1c01bf7c118
Revises: 8d15840e6016
Create Date: 2026-05-15 21:05:00.330959

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a1c01bf7c118'
down_revision: str | None = '8d15840e6016'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plattform_beitraege',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('welt', sa.String(length=20), nullable=False),
    sa.Column('schritt_nr', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulationen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plattform_beitraege_autor'), 'plattform_beitraege', ['autor'], unique=False)
    op.create_index(op.f('ix_plattform_beitraege_simulation_id'), 'plattform_beitraege', ['simulation_id'], unique=False)
    op.create_table('plattform_folgt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('welt', sa.String(length=20), nullable=False),
    sa.Column('folger', sa.String(length=200), nullable=False),
    sa.Column('gefolgter', sa.String(length=200), nullable=False),
    sa.Column('schritt_nr', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulationen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plattform_folgt_folger'), 'plattform_folgt', ['folger'], unique=False)
    op.create_index(op.f('ix_plattform_folgt_gefolgter'), 'plattform_folgt', ['gefolgter'], unique=False)
    op.create_index(op.f('ix_plattform_folgt_simulation_id'), 'plattform_folgt', ['simulation_id'], unique=False)
    op.create_table('plattform_reaktionen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('welt', sa.String(length=20), nullable=False),
    sa.Column('schritt_nr', sa.Integer(), nullable=False),
    sa.Column('beitrag_id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('inhalt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['beitrag_id'], ['plattform_beitraege.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulationen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plattform_reaktionen_autor'), 'plattform_reaktionen', ['autor'], unique=False)
    op.create_index(op.f('ix_plattform_reaktionen_simulation_id'), 'plattform_reaktionen', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plattform_reaktionen_simulation_id'), table_name='plattform_reaktionen')
    op.drop_index(op.f('ix_plattform_reaktionen_autor'), table_name='plattform_reaktionen')
    op.drop_table('plattform_reaktionen')
    op.drop_index(op.f('ix_plattform_folgt_simulation_id'), table_name='plattform_folgt')
    op.drop_index(op.f('ix_plattform_folgt_gefolgter'), table_name='plattform_folgt')
    op.drop_index(op.f('ix_plattform_folgt_folger'), table_name='plattform_folgt')
    op.drop_table('plattform_folgt')
    op.drop_index(op.f('ix_plattform_beitraege_simulation_id'), table_name='plattform_beitraege')
    op.drop_index(op.f('ix_plattform_beitraege_autor'), table_name='plattform_beitraege')
    op.drop_table('plattform_beitraege')
    # ### end Alembic commands ###
